// Code generated by protoc-gen-go.
// source: claim.proto
// DO NOT EDIT!

/*
Package protoclaim is a generated protocol buffer package.

It is generated from these files:
	claim.proto

It has these top-level messages:
	ProtoListClaim
*/
package protoclaim

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ProtoListClaim struct {
	Claims           []*ProtoListClaim_ProtoClaim `protobuf:"bytes,1,rep,name=Claims" json:"Claims,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *ProtoListClaim) Reset()         { *m = ProtoListClaim{} }
func (m *ProtoListClaim) String() string { return proto.CompactTextString(m) }
func (*ProtoListClaim) ProtoMessage()    {}

func (m *ProtoListClaim) GetClaims() []*ProtoListClaim_ProtoClaim {
	if m != nil {
		return m.Claims
	}
	return nil
}

type ProtoListClaim_ProtoClaim struct {
	GLB_OE_ID                   *float64 `protobuf:"fixed64,1,opt,name=GLB_OE_ID" json:"GLB_OE_ID,omitempty"`
	CLM_RK                      *float64 `protobuf:"fixed64,2,opt,name=CLM_RK" json:"CLM_RK,omitempty"`
	CLM_BUS_ID                  *string  `protobuf:"bytes,3,opt,name=CLM_BUS_ID" json:"CLM_BUS_ID,omitempty"`
	ABT_DT_ZERO                 *int64   `protobuf:"varint,4,opt,name=ABT_DT_ZERO" json:"ABT_DT_ZERO,omitempty"`
	CLM_STTS_CD                 *string  `protobuf:"bytes,5,opt,name=CLM_STTS_CD" json:"CLM_STTS_CD,omitempty"`
	CLM_TYP_CD                  *string  `protobuf:"bytes,6,opt,name=CLM_TYP_CD" json:"CLM_TYP_CD,omitempty"`
	CLM_CVRG_TYP                *string  `protobuf:"bytes,7,opt,name=CLM_CVRG_TYP" json:"CLM_CVRG_TYP,omitempty"`
	CLM_REASON_CD               *string  `protobuf:"bytes,8,opt,name=CLM_REASON_CD" json:"CLM_REASON_CD,omitempty"`
	CLM_DMG_DTL_CD              *string  `protobuf:"bytes,9,opt,name=CLM_DMG_DTL_CD" json:"CLM_DMG_DTL_CD,omitempty"`
	CLM_INDMNTY_AMT             *float64 `protobuf:"fixed64,10,opt,name=CLM_INDMNTY_AMT" json:"CLM_INDMNTY_AMT,omitempty"`
	CLM_RSRV_AMT                *float64 `protobuf:"fixed64,11,opt,name=CLM_RSRV_AMT" json:"CLM_RSRV_AMT,omitempty"`
	CLM_INITL_RSRV_AMT          *float64 `protobuf:"fixed64,12,opt,name=CLM_INITL_RSRV_AMT" json:"CLM_INITL_RSRV_AMT,omitempty"`
	DIFF_INTL_RSRV_PYMNT        *float64 `protobuf:"fixed64,13,opt,name=DIFF_INTL_RSRV_PYMNT" json:"DIFF_INTL_RSRV_PYMNT,omitempty"`
	CLM_FEE_AMT                 *float64 `protobuf:"fixed64,14,opt,name=CLM_FEE_AMT" json:"CLM_FEE_AMT,omitempty"`
	TOT_CLM_AMT                 *float64 `protobuf:"fixed64,15,opt,name=TOT_CLM_AMT" json:"TOT_CLM_AMT,omitempty"`
	INCDNT_DTTM                 *int64   `protobuf:"varint,16,opt,name=INCDNT_DTTM" json:"INCDNT_DTTM,omitempty"`
	INCDNT_HOUR_OF_DAY          *float64 `protobuf:"fixed64,17,opt,name=INCDNT_HOUR_OF_DAY" json:"INCDNT_HOUR_OF_DAY,omitempty"`
	INCDNT_DAY_OF_WEEK          *float64 `protobuf:"fixed64,18,opt,name=INCDNT_DAY_OF_WEEK" json:"INCDNT_DAY_OF_WEEK,omitempty"`
	CLM_RGSTR_DTTM              *int64   `protobuf:"varint,19,opt,name=CLM_RGSTR_DTTM" json:"CLM_RGSTR_DTTM,omitempty"`
	DAYS_INCDNT_RGSTR           *float64 `protobuf:"fixed64,20,opt,name=DAYS_INCDNT_RGSTR" json:"DAYS_INCDNT_RGSTR,omitempty"`
	CLM_LAST_CLSD_DTTM          *int64   `protobuf:"varint,21,opt,name=CLM_LAST_CLSD_DTTM" json:"CLM_LAST_CLSD_DTTM,omitempty"`
	CLM_LAST_STTLM_DTTM         *int64   `protobuf:"varint,22,opt,name=CLM_LAST_STTLM_DTTM" json:"CLM_LAST_STTLM_DTTM,omitempty"`
	CLM_LGL_FLG                 *float64 `protobuf:"fixed64,23,opt,name=CLM_LGL_FLG" json:"CLM_LGL_FLG,omitempty"`
	CLM_NOTIF_CHNL_CD           *string  `protobuf:"bytes,24,opt,name=CLM_NOTIF_CHNL_CD" json:"CLM_NOTIF_CHNL_CD,omitempty"`
	CLM_NOTIF_SRC_CD            *string  `protobuf:"bytes,25,opt,name=CLM_NOTIF_SRC_CD" json:"CLM_NOTIF_SRC_CD,omitempty"`
	CLM_NOTIF_TO_CLM_HNDL_DTTM  *int64   `protobuf:"varint,26,opt,name=CLM_NOTIF_TO_CLM_HNDL_DTTM" json:"CLM_NOTIF_TO_CLM_HNDL_DTTM,omitempty"`
	DAYS_NOTIF_CHNL_HNDL        *float64 `protobuf:"fixed64,27,opt,name=DAYS_NOTIF_CHNL_HNDL" json:"DAYS_NOTIF_CHNL_HNDL,omitempty"`
	CLM_RCVR_PAID_AMT           *float64 `protobuf:"fixed64,28,opt,name=CLM_RCVR_PAID_AMT" json:"CLM_RCVR_PAID_AMT,omitempty"`
	CLM_RSRV_STTLM_TRTY_AMT     *float64 `protobuf:"fixed64,29,opt,name=CLM_RSRV_STTLM_TRTY_AMT" json:"CLM_RSRV_STTLM_TRTY_AMT,omitempty"`
	INCDNT_DESC                 *string  `protobuf:"bytes,30,opt,name=INCDNT_DESC" json:"INCDNT_DESC,omitempty"`
	INCDNT_LOC_DESC             *string  `protobuf:"bytes,31,opt,name=INCDNT_LOC_DESC" json:"INCDNT_LOC_DESC,omitempty"`
	INCDNT_LOC_GPS_CRDNT        *string  `protobuf:"bytes,32,opt,name=INCDNT_LOC_GPS_CRDNT" json:"INCDNT_LOC_GPS_CRDNT,omitempty"`
	INCDNT_MULTI_VEH_INCDNT_FLG *float64 `protobuf:"fixed64,33,opt,name=INCDNT_MULTI_VEH_INCDNT_FLG" json:"INCDNT_MULTI_VEH_INCDNT_FLG,omitempty"`
	INCDNT_OTH_OBJ_FLG          *float64 `protobuf:"fixed64,34,opt,name=INCDNT_OTH_OBJ_FLG" json:"INCDNT_OTH_OBJ_FLG,omitempty"`
	INCDNT_PLCE_AT_SCENE_FLG    *float64 `protobuf:"fixed64,35,opt,name=INCDNT_PLCE_AT_SCENE_FLG" json:"INCDNT_PLCE_AT_SCENE_FLG,omitempty"`
	INCDNT_TOTAL_VEH_NO         *float64 `protobuf:"fixed64,36,opt,name=INCDNT_TOTAL_VEH_NO" json:"INCDNT_TOTAL_VEH_NO,omitempty"`
	INCDNT_CNTRY_CD             *string  `protobuf:"bytes,37,opt,name=INCDNT_CNTRY_CD" json:"INCDNT_CNTRY_CD,omitempty"`
	INCDNT_ABROAD_FLG           *float64 `protobuf:"fixed64,38,opt,name=INCDNT_ABROAD_FLG" json:"INCDNT_ABROAD_FLG,omitempty"`
	INCDNT_ADDR_LN_1            *string  `protobuf:"bytes,39,opt,name=INCDNT_ADDR_LN_1" json:"INCDNT_ADDR_LN_1,omitempty"`
	INCDNT_CITY_NM              *string  `protobuf:"bytes,40,opt,name=INCDNT_CITY_NM" json:"INCDNT_CITY_NM,omitempty"`
	INCDNT_POSTAL_CD            *string  `protobuf:"bytes,41,opt,name=INCDNT_POSTAL_CD" json:"INCDNT_POSTAL_CD,omitempty"`
	INCDNT_DISTRICT_NM          *string  `protobuf:"bytes,42,opt,name=INCDNT_DISTRICT_NM" json:"INCDNT_DISTRICT_NM,omitempty"`
	CNTRCT_BUS_ID               *string  `protobuf:"bytes,43,opt,name=CNTRCT_BUS_ID" json:"CNTRCT_BUS_ID,omitempty"`
	CNTRCT_ISSUE_DTTM           *int64   `protobuf:"varint,44,opt,name=CNTRCT_ISSUE_DTTM" json:"CNTRCT_ISSUE_DTTM,omitempty"`
	DAYS_INCDNT_CNTRCT_ISSUE    *float64 `protobuf:"fixed64,45,opt,name=DAYS_INCDNT_CNTRCT_ISSUE" json:"DAYS_INCDNT_CNTRCT_ISSUE,omitempty"`
	DAYS_RGSTR_CNTRCT_ISSUE     *float64 `protobuf:"fixed64,46,opt,name=DAYS_RGSTR_CNTRCT_ISSUE" json:"DAYS_RGSTR_CNTRCT_ISSUE,omitempty"`
	CNTRCT_NEXT_RNWL_DTTM       *int64   `protobuf:"varint,47,opt,name=CNTRCT_NEXT_RNWL_DTTM" json:"CNTRCT_NEXT_RNWL_DTTM,omitempty"`
	CNTRCT_EXPRY_DTTM           *int64   `protobuf:"varint,48,opt,name=CNTRCT_EXPRY_DTTM" json:"CNTRCT_EXPRY_DTTM,omitempty"`
	DAYS_INCDNT_CNTRCT_EXPRY    *float64 `protobuf:"fixed64,49,opt,name=DAYS_INCDNT_CNTRCT_EXPRY" json:"DAYS_INCDNT_CNTRCT_EXPRY,omitempty"`
	PYMT_METHOD_CD              *string  `protobuf:"bytes,50,opt,name=PYMT_METHOD_CD" json:"PYMT_METHOD_CD,omitempty"`
	PYMT_MODE_CD                *string  `protobuf:"bytes,51,opt,name=PYMT_MODE_CD" json:"PYMT_MODE_CD,omitempty"`
	GWP_ANN_AMT                 *float64 `protobuf:"fixed64,52,opt,name=GWP_ANN_AMT" json:"GWP_ANN_AMT,omitempty"`
	TSI_AMT                     *float64 `protobuf:"fixed64,53,opt,name=TSI_AMT" json:"TSI_AMT,omitempty"`
	RATIO_CLM_AMT_TSI_AMT       *float64 `protobuf:"fixed64,54,opt,name=RATIO_CLM_AMT_TSI_AMT" json:"RATIO_CLM_AMT_TSI_AMT,omitempty"`
	PLCY_BUS_ID                 *string  `protobuf:"bytes,55,opt,name=PLCY_BUS_ID" json:"PLCY_BUS_ID,omitempty"`
	PLCY_CNTRCT_CTGRY_CD        *string  `protobuf:"bytes,56,opt,name=PLCY_CNTRCT_CTGRY_CD" json:"PLCY_CNTRCT_CTGRY_CD,omitempty"`
	PLCY_CNTRCT_STTS_CD         *string  `protobuf:"bytes,57,opt,name=PLCY_CNTRCT_STTS_CD" json:"PLCY_CNTRCT_STTS_CD,omitempty"`
	PLCY_CNTRCT_TYP_CD          *string  `protobuf:"bytes,58,opt,name=PLCY_CNTRCT_TYP_CD" json:"PLCY_CNTRCT_TYP_CD,omitempty"`
	PLCY_PRM_ACCT_STTS_CD       *string  `protobuf:"bytes,59,opt,name=PLCY_PRM_ACCT_STTS_CD" json:"PLCY_PRM_ACCT_STTS_CD,omitempty"`
	PLCY_MNTH_PYMT_DUE_DAY_NO   *float64 `protobuf:"fixed64,60,opt,name=PLCY_MNTH_PYMT_DUE_DAY_NO" json:"PLCY_MNTH_PYMT_DUE_DAY_NO,omitempty"`
	PLCY_PRM_CVR_FLG            *float64 `protobuf:"fixed64,61,opt,name=PLCY_PRM_CVR_FLG" json:"PLCY_PRM_CVR_FLG,omitempty"`
	PLCY_PRM_CVR_FLG_UPDT_DT    *int64   `protobuf:"varint,62,opt,name=PLCY_PRM_CVR_FLG_UPDT_DT" json:"PLCY_PRM_CVR_FLG_UPDT_DT,omitempty"`
	PLCY_PRM_PAID_UNTIL_DT      *int64   `protobuf:"varint,63,opt,name=PLCY_PRM_PAID_UNTIL_DT" json:"PLCY_PRM_PAID_UNTIL_DT,omitempty"`
	PLCY_ISSUE_DTTM             *int64   `protobuf:"varint,64,opt,name=PLCY_ISSUE_DTTM" json:"PLCY_ISSUE_DTTM,omitempty"`
	DAYS_INCDNT_PLCY_ISSUE      *float64 `protobuf:"fixed64,65,opt,name=DAYS_INCDNT_PLCY_ISSUE" json:"DAYS_INCDNT_PLCY_ISSUE,omitempty"`
	DAYS_RGSTR_PLCY_ISSUE       *float64 `protobuf:"fixed64,66,opt,name=DAYS_RGSTR_PLCY_ISSUE" json:"DAYS_RGSTR_PLCY_ISSUE,omitempty"`
	PLCY_NEXT_RNWL_DTTM         *int64   `protobuf:"varint,67,opt,name=PLCY_NEXT_RNWL_DTTM" json:"PLCY_NEXT_RNWL_DTTM,omitempty"`
	PLCY_EXPRY_DTTM             *int64   `protobuf:"varint,68,opt,name=PLCY_EXPRY_DTTM" json:"PLCY_EXPRY_DTTM,omitempty"`
	DAYS_INCDNT_PLCY_EXPRY      *float64 `protobuf:"fixed64,69,opt,name=DAYS_INCDNT_PLCY_EXPRY" json:"DAYS_INCDNT_PLCY_EXPRY,omitempty"`
	CLM_PLCY_HLD_RSPN_PCT       *float64 `protobuf:"fixed64,70,opt,name=CLM_PLCY_HLD_RSPN_PCT" json:"CLM_PLCY_HLD_RSPN_PCT,omitempty"`
	FRAUD_FLG                   *string  `protobuf:"bytes,71,opt,name=FRAUD_FLG" json:"FRAUD_FLG,omitempty"`
	INVSTGT_FLG                 *float64 `protobuf:"fixed64,72,opt,name=INVSTGT_FLG" json:"INVSTGT_FLG,omitempty"`
	INVSTGT_STRT_DT             *int64   `protobuf:"varint,73,opt,name=INVSTGT_STRT_DT" json:"INVSTGT_STRT_DT,omitempty"`
	INVSTGT_END_DT              *int64   `protobuf:"varint,74,opt,name=INVSTGT_END_DT" json:"INVSTGT_END_DT,omitempty"`
	BI_FLG                      *float64 `protobuf:"fixed64,75,opt,name=BI_FLG" json:"BI_FLG,omitempty"`
	OBJ_TTL_LOSS_FLG            *float64 `protobuf:"fixed64,76,opt,name=OBJ_TTL_LOSS_FLG" json:"OBJ_TTL_LOSS_FLG,omitempty"`
	CLM_OBJ_ROLE_CD             *string  `protobuf:"bytes,77,opt,name=CLM_OBJ_ROLE_CD" json:"CLM_OBJ_ROLE_CD,omitempty"`
	OBJ_TYP_CD                  *string  `protobuf:"bytes,78,opt,name=OBJ_TYP_CD" json:"OBJ_TYP_CD,omitempty"`
	VEH_TYP_CD                  *string  `protobuf:"bytes,79,opt,name=VEH_TYP_CD" json:"VEH_TYP_CD,omitempty"`
	VEH_USE_TYP_CD              *string  `protobuf:"bytes,80,opt,name=VEH_USE_TYP_CD" json:"VEH_USE_TYP_CD,omitempty"`
	OBJ_BUS_ID                  *string  `protobuf:"bytes,81,opt,name=OBJ_BUS_ID" json:"OBJ_BUS_ID,omitempty"`
	VEH_VIN                     *string  `protobuf:"bytes,82,opt,name=VEH_VIN" json:"VEH_VIN,omitempty"`
	VEH_MNFCTR_DT               *string  `protobuf:"bytes,83,opt,name=VEH_MNFCTR_DT" json:"VEH_MNFCTR_DT,omitempty"`
	VEH_AGE_YRS                 *float64 `protobuf:"fixed64,84,opt,name=VEH_AGE_YRS" json:"VEH_AGE_YRS,omitempty"`
	VEH_COLOR_TXT               *string  `protobuf:"bytes,85,opt,name=VEH_COLOR_TXT" json:"VEH_COLOR_TXT,omitempty"`
	VEH_MNFCTR_NM               *string  `protobuf:"bytes,86,opt,name=VEH_MNFCTR_NM" json:"VEH_MNFCTR_NM,omitempty"`
	VEH_MODEL_TXT               *string  `protobuf:"bytes,87,opt,name=VEH_MODEL_TXT" json:"VEH_MODEL_TXT,omitempty"`
	VEH_MODEL_YR_NO             *string  `protobuf:"bytes,88,opt,name=VEH_MODEL_YR_NO" json:"VEH_MODEL_YR_NO,omitempty"`
	VEH_PRCH_AMT                *float64 `protobuf:"fixed64,89,opt,name=VEH_PRCH_AMT" json:"VEH_PRCH_AMT,omitempty"`
	VEH_LEASED_FLG              *float64 `protobuf:"fixed64,90,opt,name=VEH_LEASED_FLG" json:"VEH_LEASED_FLG,omitempty"`
	VEH_LCNS_PLATE_NO_TXT       *string  `protobuf:"bytes,91,opt,name=VEH_LCNS_PLATE_NO_TXT" json:"VEH_LCNS_PLATE_NO_TXT,omitempty"`
	VEH_PRCH_DT                 *int64   `protobuf:"varint,92,opt,name=VEH_PRCH_DT" json:"VEH_PRCH_DT,omitempty"`
	RATIO_CLM_AMT_VEH_PRCH_AMT  *float64 `protobuf:"fixed64,93,opt,name=RATIO_CLM_AMT_VEH_PRCH_AMT" json:"RATIO_CLM_AMT_VEH_PRCH_AMT,omitempty"`
	TP_VEH_AGE_YRS              *float64 `protobuf:"fixed64,94,opt,name=TP_VEH_AGE_YRS" json:"TP_VEH_AGE_YRS,omitempty"`
	PLCE_RPRT_FLG               *float64 `protobuf:"fixed64,95,opt,name=PLCE_RPRT_FLG" json:"PLCE_RPRT_FLG,omitempty"`
	PRTY_TYP_CD                 *string  `protobuf:"bytes,96,opt,name=PRTY_TYP_CD" json:"PRTY_TYP_CD,omitempty"`
	LE_BUS_TYP_CD               *string  `protobuf:"bytes,97,opt,name=LE_BUS_TYP_CD" json:"LE_BUS_TYP_CD,omitempty"`
	PE_GENDER_TYP_CD            *string  `protobuf:"bytes,98,opt,name=PE_GENDER_TYP_CD" json:"PE_GENDER_TYP_CD,omitempty"`
	PE_MRTL_STTS_CD             *string  `protobuf:"bytes,99,opt,name=PE_MRTL_STTS_CD" json:"PE_MRTL_STTS_CD,omitempty"`
	PE_OCC_TYP_CD               *string  `protobuf:"bytes,100,opt,name=PE_OCC_TYP_CD" json:"PE_OCC_TYP_CD,omitempty"`
	PRTY_TAX_NO_TXT             *string  `protobuf:"bytes,101,opt,name=PRTY_TAX_NO_TXT" json:"PRTY_TAX_NO_TXT,omitempty"`
	PRTY_WATCH_LIST_FLG         *float64 `protobuf:"fixed64,102,opt,name=PRTY_WATCH_LIST_FLG" json:"PRTY_WATCH_LIST_FLG,omitempty"`
	PLCY_HLD_NM                 *string  `protobuf:"bytes,103,opt,name=PLCY_HLD_NM" json:"PLCY_HLD_NM,omitempty"`
	PE_BIRTH_DT                 *int64   `protobuf:"varint,104,opt,name=PE_BIRTH_DT" json:"PE_BIRTH_DT,omitempty"`
	PLCY_HLD_AGE                *float64 `protobuf:"fixed64,105,opt,name=PLCY_HLD_AGE" json:"PLCY_HLD_AGE,omitempty"`
	PRTY_CNTRY_CD               *string  `protobuf:"bytes,106,opt,name=PRTY_CNTRY_CD" json:"PRTY_CNTRY_CD,omitempty"`
	PRTY_ADDR_LN_1              *string  `protobuf:"bytes,107,opt,name=PRTY_ADDR_LN_1" json:"PRTY_ADDR_LN_1,omitempty"`
	PRTY_CITY_NM                *string  `protobuf:"bytes,108,opt,name=PRTY_CITY_NM" json:"PRTY_CITY_NM,omitempty"`
	PRTY_POSTAL_CD              *string  `protobuf:"bytes,109,opt,name=PRTY_POSTAL_CD" json:"PRTY_POSTAL_CD,omitempty"`
	PRTY_DISTRICT_NM            *string  `protobuf:"bytes,110,opt,name=PRTY_DISTRICT_NM" json:"PRTY_DISTRICT_NM,omitempty"`
	BR002_I001                  *float64 `protobuf:"fixed64,111,opt,name=BR002_I001" json:"BR002_I001,omitempty"`
	BR002_I002                  *float64 `protobuf:"fixed64,112,opt,name=BR002_I002" json:"BR002_I002,omitempty"`
	BR002_I003                  *float64 `protobuf:"fixed64,113,opt,name=BR002_I003" json:"BR002_I003,omitempty"`
	BR002_I004                  *float64 `protobuf:"fixed64,114,opt,name=BR002_I004" json:"BR002_I004,omitempty"`
	BR002_I005                  *float64 `protobuf:"fixed64,115,opt,name=BR002_I005" json:"BR002_I005,omitempty"`
	BR002_I006                  *float64 `protobuf:"fixed64,116,opt,name=BR002_I006" json:"BR002_I006,omitempty"`
	BR002_I007                  *float64 `protobuf:"fixed64,117,opt,name=BR002_I007" json:"BR002_I007,omitempty"`
	BR002_I008                  *float64 `protobuf:"fixed64,118,opt,name=BR002_I008" json:"BR002_I008,omitempty"`
	BR002_I009                  *float64 `protobuf:"fixed64,119,opt,name=BR002_I009" json:"BR002_I009,omitempty"`
	BR002_I010                  *float64 `protobuf:"fixed64,120,opt,name=BR002_I010" json:"BR002_I010,omitempty"`
	BR002_I011                  *float64 `protobuf:"fixed64,121,opt,name=BR002_I011" json:"BR002_I011,omitempty"`
	BR002_I012                  *float64 `protobuf:"fixed64,122,opt,name=BR002_I012" json:"BR002_I012,omitempty"`
	BR002_I013                  *float64 `protobuf:"fixed64,123,opt,name=BR002_I013" json:"BR002_I013,omitempty"`
	BR002_I014                  *float64 `protobuf:"fixed64,124,opt,name=BR002_I014" json:"BR002_I014,omitempty"`
	BR002_I015                  *float64 `protobuf:"fixed64,125,opt,name=BR002_I015" json:"BR002_I015,omitempty"`
	BR002_I016                  *float64 `protobuf:"fixed64,126,opt,name=BR002_I016" json:"BR002_I016,omitempty"`
	BR002_I017                  *float64 `protobuf:"fixed64,127,opt,name=BR002_I017" json:"BR002_I017,omitempty"`
	BR002_I018                  *float64 `protobuf:"fixed64,128,opt,name=BR002_I018" json:"BR002_I018,omitempty"`
	BR002_I019                  *float64 `protobuf:"fixed64,129,opt,name=BR002_I019" json:"BR002_I019,omitempty"`
	BR002_I020                  *float64 `protobuf:"fixed64,130,opt,name=BR002_I020" json:"BR002_I020,omitempty"`
	BR002_I021                  *float64 `protobuf:"fixed64,131,opt,name=BR002_I021" json:"BR002_I021,omitempty"`
	BR002_I022                  *float64 `protobuf:"fixed64,132,opt,name=BR002_I022" json:"BR002_I022,omitempty"`
	BR002_I023                  *float64 `protobuf:"fixed64,133,opt,name=BR002_I023" json:"BR002_I023,omitempty"`
	BR002_I024                  *float64 `protobuf:"fixed64,134,opt,name=BR002_I024" json:"BR002_I024,omitempty"`
	BR002_I025                  *float64 `protobuf:"fixed64,135,opt,name=BR002_I025" json:"BR002_I025,omitempty"`
	BR002_I026                  *float64 `protobuf:"fixed64,136,opt,name=BR002_I026" json:"BR002_I026,omitempty"`
	BR002_I027                  *float64 `protobuf:"fixed64,137,opt,name=BR002_I027" json:"BR002_I027,omitempty"`
	BR002_I028                  *float64 `protobuf:"fixed64,138,opt,name=BR002_I028" json:"BR002_I028,omitempty"`
	BR002_I029                  *float64 `protobuf:"fixed64,139,opt,name=BR002_I029" json:"BR002_I029,omitempty"`
	BR002_I030                  *float64 `protobuf:"fixed64,140,opt,name=BR002_I030" json:"BR002_I030,omitempty"`
	BR003_I001                  *float64 `protobuf:"fixed64,141,opt,name=BR003_I001" json:"BR003_I001,omitempty"`
	BR003_I002                  *float64 `protobuf:"fixed64,142,opt,name=BR003_I002" json:"BR003_I002,omitempty"`
	BR003_I003                  *float64 `protobuf:"fixed64,143,opt,name=BR003_I003" json:"BR003_I003,omitempty"`
	BR003_I004                  *float64 `protobuf:"fixed64,144,opt,name=BR003_I004" json:"BR003_I004,omitempty"`
	BR003_I005                  *float64 `protobuf:"fixed64,145,opt,name=BR003_I005" json:"BR003_I005,omitempty"`
	BR003_I006                  *float64 `protobuf:"fixed64,146,opt,name=BR003_I006" json:"BR003_I006,omitempty"`
	BR003_I007                  *float64 `protobuf:"fixed64,147,opt,name=BR003_I007" json:"BR003_I007,omitempty"`
	BR003_I008                  *float64 `protobuf:"fixed64,148,opt,name=BR003_I008" json:"BR003_I008,omitempty"`
	BR003_I009                  *float64 `protobuf:"fixed64,149,opt,name=BR003_I009" json:"BR003_I009,omitempty"`
	BR003_I010                  *float64 `protobuf:"fixed64,150,opt,name=BR003_I010" json:"BR003_I010,omitempty"`
	BR003_I011                  *float64 `protobuf:"fixed64,151,opt,name=BR003_I011" json:"BR003_I011,omitempty"`
	BR003_I012                  *float64 `protobuf:"fixed64,152,opt,name=BR003_I012" json:"BR003_I012,omitempty"`
	BR003_I013                  *float64 `protobuf:"fixed64,153,opt,name=BR003_I013" json:"BR003_I013,omitempty"`
	BR003_I014                  *float64 `protobuf:"fixed64,154,opt,name=BR003_I014" json:"BR003_I014,omitempty"`
	BR003_I015                  *float64 `protobuf:"fixed64,155,opt,name=BR003_I015" json:"BR003_I015,omitempty"`
	BR003_I016                  *float64 `protobuf:"fixed64,156,opt,name=BR003_I016" json:"BR003_I016,omitempty"`
	BR003_I017                  *float64 `protobuf:"fixed64,157,opt,name=BR003_I017" json:"BR003_I017,omitempty"`
	BR003_I018                  *float64 `protobuf:"fixed64,158,opt,name=BR003_I018" json:"BR003_I018,omitempty"`
	BR003_I019                  *float64 `protobuf:"fixed64,159,opt,name=BR003_I019" json:"BR003_I019,omitempty"`
	BR003_I020                  *float64 `protobuf:"fixed64,160,opt,name=BR003_I020" json:"BR003_I020,omitempty"`
	BR003_I021                  *float64 `protobuf:"fixed64,161,opt,name=BR003_I021" json:"BR003_I021,omitempty"`
	BR003_I022                  *float64 `protobuf:"fixed64,162,opt,name=BR003_I022" json:"BR003_I022,omitempty"`
	BR003_I023                  *float64 `protobuf:"fixed64,163,opt,name=BR003_I023" json:"BR003_I023,omitempty"`
	BR003_I024                  *float64 `protobuf:"fixed64,164,opt,name=BR003_I024" json:"BR003_I024,omitempty"`
	BR003_I025                  *float64 `protobuf:"fixed64,165,opt,name=BR003_I025" json:"BR003_I025,omitempty"`
	BR003_I026                  *float64 `protobuf:"fixed64,166,opt,name=BR003_I026" json:"BR003_I026,omitempty"`
	BR003_I027                  *float64 `protobuf:"fixed64,167,opt,name=BR003_I027" json:"BR003_I027,omitempty"`
	BR003_I028                  *float64 `protobuf:"fixed64,168,opt,name=BR003_I028" json:"BR003_I028,omitempty"`
	BR003_I029                  *float64 `protobuf:"fixed64,169,opt,name=BR003_I029" json:"BR003_I029,omitempty"`
	BR003_I030                  *float64 `protobuf:"fixed64,170,opt,name=BR003_I030" json:"BR003_I030,omitempty"`
	BR003_I031                  *float64 `protobuf:"fixed64,171,opt,name=BR003_I031" json:"BR003_I031,omitempty"`
	BR003_I032                  *float64 `protobuf:"fixed64,172,opt,name=BR003_I032" json:"BR003_I032,omitempty"`
	BR003_I033                  *float64 `protobuf:"fixed64,173,opt,name=BR003_I033" json:"BR003_I033,omitempty"`
	BR003_I034                  *float64 `protobuf:"fixed64,174,opt,name=BR003_I034" json:"BR003_I034,omitempty"`
	BR003_I035                  *float64 `protobuf:"fixed64,175,opt,name=BR003_I035" json:"BR003_I035,omitempty"`
	BR006_I001                  *float64 `protobuf:"fixed64,176,opt,name=BR006_I001" json:"BR006_I001,omitempty"`
	BR006_I002                  *float64 `protobuf:"fixed64,177,opt,name=BR006_I002" json:"BR006_I002,omitempty"`
	BR006_I003                  *float64 `protobuf:"fixed64,178,opt,name=BR006_I003" json:"BR006_I003,omitempty"`
	BR006_I004                  *float64 `protobuf:"fixed64,179,opt,name=BR006_I004" json:"BR006_I004,omitempty"`
	BR006_I005                  *float64 `protobuf:"fixed64,180,opt,name=BR006_I005" json:"BR006_I005,omitempty"`
	BR006_I006                  *float64 `protobuf:"fixed64,181,opt,name=BR006_I006" json:"BR006_I006,omitempty"`
	BR006_I007                  *float64 `protobuf:"fixed64,182,opt,name=BR006_I007" json:"BR006_I007,omitempty"`
	BR012_I001                  *float64 `protobuf:"fixed64,183,opt,name=BR012_I001" json:"BR012_I001,omitempty"`
	BR012_I002                  *float64 `protobuf:"fixed64,184,opt,name=BR012_I002" json:"BR012_I002,omitempty"`
	BR012_I003                  *float64 `protobuf:"fixed64,185,opt,name=BR012_I003" json:"BR012_I003,omitempty"`
	BR012_I004                  *float64 `protobuf:"fixed64,186,opt,name=BR012_I004" json:"BR012_I004,omitempty"`
	BR012_I005                  *float64 `protobuf:"fixed64,187,opt,name=BR012_I005" json:"BR012_I005,omitempty"`
	BR031_I001                  *float64 `protobuf:"fixed64,188,opt,name=BR031_I001" json:"BR031_I001,omitempty"`
	BR031_I002                  *float64 `protobuf:"fixed64,189,opt,name=BR031_I002" json:"BR031_I002,omitempty"`
	BR031_I003                  *float64 `protobuf:"fixed64,190,opt,name=BR031_I003" json:"BR031_I003,omitempty"`
	BR031_I004                  *float64 `protobuf:"fixed64,191,opt,name=BR031_I004" json:"BR031_I004,omitempty"`
	BR031_I005                  *float64 `protobuf:"fixed64,192,opt,name=BR031_I005" json:"BR031_I005,omitempty"`
	BR031_I006                  *float64 `protobuf:"fixed64,193,opt,name=BR031_I006" json:"BR031_I006,omitempty"`
	BR031_I007                  *float64 `protobuf:"fixed64,194,opt,name=BR031_I007" json:"BR031_I007,omitempty"`
	BR038_I001                  *float64 `protobuf:"fixed64,195,opt,name=BR038_I001" json:"BR038_I001,omitempty"`
	BR038_I002                  *float64 `protobuf:"fixed64,196,opt,name=BR038_I002" json:"BR038_I002,omitempty"`
	BR038_I003                  *float64 `protobuf:"fixed64,197,opt,name=BR038_I003" json:"BR038_I003,omitempty"`
	BR038_I004                  *float64 `protobuf:"fixed64,198,opt,name=BR038_I004" json:"BR038_I004,omitempty"`
	BR038_I005                  *float64 `protobuf:"fixed64,199,opt,name=BR038_I005" json:"BR038_I005,omitempty"`
	BR038_I006                  *float64 `protobuf:"fixed64,200,opt,name=BR038_I006" json:"BR038_I006,omitempty"`
	BR055_I001                  *float64 `protobuf:"fixed64,201,opt,name=BR055_I001" json:"BR055_I001,omitempty"`
	BR055_I002                  *float64 `protobuf:"fixed64,202,opt,name=BR055_I002" json:"BR055_I002,omitempty"`
	BR055_I003                  *float64 `protobuf:"fixed64,203,opt,name=BR055_I003" json:"BR055_I003,omitempty"`
	BR055_I004                  *float64 `protobuf:"fixed64,204,opt,name=BR055_I004" json:"BR055_I004,omitempty"`
	BR060_I001                  *float64 `protobuf:"fixed64,205,opt,name=BR060_I001" json:"BR060_I001,omitempty"`
	BR060_I002                  *float64 `protobuf:"fixed64,206,opt,name=BR060_I002" json:"BR060_I002,omitempty"`
	BR060_I003                  *float64 `protobuf:"fixed64,207,opt,name=BR060_I003" json:"BR060_I003,omitempty"`
	BR060_I004                  *float64 `protobuf:"fixed64,208,opt,name=BR060_I004" json:"BR060_I004,omitempty"`
	BR060_I005                  *float64 `protobuf:"fixed64,209,opt,name=BR060_I005" json:"BR060_I005,omitempty"`
	BR060_I006                  *float64 `protobuf:"fixed64,210,opt,name=BR060_I006" json:"BR060_I006,omitempty"`
	BR063_I001                  *float64 `protobuf:"fixed64,211,opt,name=BR063_I001" json:"BR063_I001,omitempty"`
	BR063_I002                  *float64 `protobuf:"fixed64,212,opt,name=BR063_I002" json:"BR063_I002,omitempty"`
	BR063_I003                  *float64 `protobuf:"fixed64,213,opt,name=BR063_I003" json:"BR063_I003,omitempty"`
	BR063_I004                  *float64 `protobuf:"fixed64,214,opt,name=BR063_I004" json:"BR063_I004,omitempty"`
	BR063_I005                  *float64 `protobuf:"fixed64,215,opt,name=BR063_I005" json:"BR063_I005,omitempty"`
	BR076_I001                  *float64 `protobuf:"fixed64,216,opt,name=BR076_I001" json:"BR076_I001,omitempty"`
	BR095_I001                  *float64 `protobuf:"fixed64,217,opt,name=BR095_I001" json:"BR095_I001,omitempty"`
	BR095_I002                  *float64 `protobuf:"fixed64,218,opt,name=BR095_I002" json:"BR095_I002,omitempty"`
	BR095_I003                  *float64 `protobuf:"fixed64,219,opt,name=BR095_I003" json:"BR095_I003,omitempty"`
	BR095_I004                  *float64 `protobuf:"fixed64,220,opt,name=BR095_I004" json:"BR095_I004,omitempty"`
	BR095_I005                  *float64 `protobuf:"fixed64,221,opt,name=BR095_I005" json:"BR095_I005,omitempty"`
	BR096_I001                  *float64 `protobuf:"fixed64,222,opt,name=BR096_I001" json:"BR096_I001,omitempty"`
	BR096_I002                  *float64 `protobuf:"fixed64,223,opt,name=BR096_I002" json:"BR096_I002,omitempty"`
	BR096_I003                  *float64 `protobuf:"fixed64,224,opt,name=BR096_I003" json:"BR096_I003,omitempty"`
	BR096_I004                  *float64 `protobuf:"fixed64,225,opt,name=BR096_I004" json:"BR096_I004,omitempty"`
	BR096_I005                  *float64 `protobuf:"fixed64,226,opt,name=BR096_I005" json:"BR096_I005,omitempty"`
	BR102_I001                  *float64 `protobuf:"fixed64,227,opt,name=BR102_I001" json:"BR102_I001,omitempty"`
	BR103_I001                  *float64 `protobuf:"fixed64,228,opt,name=BR103_I001" json:"BR103_I001,omitempty"`
	BR103_I002                  *float64 `protobuf:"fixed64,229,opt,name=BR103_I002" json:"BR103_I002,omitempty"`
	BR108_I001                  *float64 `protobuf:"fixed64,230,opt,name=BR108_I001" json:"BR108_I001,omitempty"`
	BR108_I002                  *float64 `protobuf:"fixed64,231,opt,name=BR108_I002" json:"BR108_I002,omitempty"`
	BR108_I003                  *float64 `protobuf:"fixed64,232,opt,name=BR108_I003" json:"BR108_I003,omitempty"`
	BR109_I001                  *float64 `protobuf:"fixed64,233,opt,name=BR109_I001" json:"BR109_I001,omitempty"`
	BR109_I002                  *float64 `protobuf:"fixed64,234,opt,name=BR109_I002" json:"BR109_I002,omitempty"`
	BR109_I003                  *float64 `protobuf:"fixed64,235,opt,name=BR109_I003" json:"BR109_I003,omitempty"`
	BR109_I004                  *float64 `protobuf:"fixed64,236,opt,name=BR109_I004" json:"BR109_I004,omitempty"`
	BR109_I005                  *float64 `protobuf:"fixed64,237,opt,name=BR109_I005" json:"BR109_I005,omitempty"`
	BR109_I006                  *float64 `protobuf:"fixed64,238,opt,name=BR109_I006" json:"BR109_I006,omitempty"`
	BR109_I007                  *float64 `protobuf:"fixed64,239,opt,name=BR109_I007" json:"BR109_I007,omitempty"`
	BR109_I008                  *float64 `protobuf:"fixed64,240,opt,name=BR109_I008" json:"BR109_I008,omitempty"`
	BR109_I009                  *float64 `protobuf:"fixed64,241,opt,name=BR109_I009" json:"BR109_I009,omitempty"`
	BR109_I010                  *float64 `protobuf:"fixed64,242,opt,name=BR109_I010" json:"BR109_I010,omitempty"`
	BR110_I001                  *float64 `protobuf:"fixed64,243,opt,name=BR110_I001" json:"BR110_I001,omitempty"`
	BR111_I001                  *float64 `protobuf:"fixed64,244,opt,name=BR111_I001" json:"BR111_I001,omitempty"`
	BR112_I001                  *float64 `protobuf:"fixed64,245,opt,name=BR112_I001" json:"BR112_I001,omitempty"`
	BR113_I001                  *float64 `protobuf:"fixed64,246,opt,name=BR113_I001" json:"BR113_I001,omitempty"`
	BR114_I001                  *float64 `protobuf:"fixed64,247,opt,name=BR114_I001" json:"BR114_I001,omitempty"`
	BR114_I002                  *float64 `protobuf:"fixed64,248,opt,name=BR114_I002" json:"BR114_I002,omitempty"`
	BR114_I003                  *float64 `protobuf:"fixed64,249,opt,name=BR114_I003" json:"BR114_I003,omitempty"`
	BR114_I004                  *float64 `protobuf:"fixed64,250,opt,name=BR114_I004" json:"BR114_I004,omitempty"`
	BR115_I001                  *float64 `protobuf:"fixed64,251,opt,name=BR115_I001" json:"BR115_I001,omitempty"`
	BR117_I001                  *float64 `protobuf:"fixed64,252,opt,name=BR117_I001" json:"BR117_I001,omitempty"`
	BR118_I001                  *float64 `protobuf:"fixed64,253,opt,name=BR118_I001" json:"BR118_I001,omitempty"`
	BR119_I001                  *float64 `protobuf:"fixed64,254,opt,name=BR119_I001" json:"BR119_I001,omitempty"`
	BR121_I001                  *float64 `protobuf:"fixed64,255,opt,name=BR121_I001" json:"BR121_I001,omitempty"`
	BR122_I001                  *float64 `protobuf:"fixed64,256,opt,name=BR122_I001" json:"BR122_I001,omitempty"`
	BR123_I001                  *float64 `protobuf:"fixed64,257,opt,name=BR123_I001" json:"BR123_I001,omitempty"`
	BR125_I001                  *float64 `protobuf:"fixed64,258,opt,name=BR125_I001" json:"BR125_I001,omitempty"`
	NEW_INVSTGT_FLG             *float64 `protobuf:"fixed64,259,opt,name=NEW_INVSTGT_FLG" json:"NEW_INVSTGT_FLG,omitempty"`
	LOAD_DATE                   *int64   `protobuf:"varint,260,opt,name=LOAD_DATE" json:"LOAD_DATE,omitempty"`
	XXX_unrecognized            []byte   `json:"-"`
}

func (m *ProtoListClaim_ProtoClaim) Reset()         { *m = ProtoListClaim_ProtoClaim{} }
func (m *ProtoListClaim_ProtoClaim) String() string { return proto.CompactTextString(m) }
func (*ProtoListClaim_ProtoClaim) ProtoMessage()    {}

func (m *ProtoListClaim_ProtoClaim) GetGLB_OE_ID() float64 {
	if m != nil && m.GLB_OE_ID != nil {
		return *m.GLB_OE_ID
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_RK() float64 {
	if m != nil && m.CLM_RK != nil {
		return *m.CLM_RK
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_BUS_ID() string {
	if m != nil && m.CLM_BUS_ID != nil {
		return *m.CLM_BUS_ID
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetABT_DT_ZERO() int64 {
	if m != nil && m.ABT_DT_ZERO != nil {
		return *m.ABT_DT_ZERO
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_STTS_CD() string {
	if m != nil && m.CLM_STTS_CD != nil {
		return *m.CLM_STTS_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_TYP_CD() string {
	if m != nil && m.CLM_TYP_CD != nil {
		return *m.CLM_TYP_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_CVRG_TYP() string {
	if m != nil && m.CLM_CVRG_TYP != nil {
		return *m.CLM_CVRG_TYP
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_REASON_CD() string {
	if m != nil && m.CLM_REASON_CD != nil {
		return *m.CLM_REASON_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_DMG_DTL_CD() string {
	if m != nil && m.CLM_DMG_DTL_CD != nil {
		return *m.CLM_DMG_DTL_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_INDMNTY_AMT() float64 {
	if m != nil && m.CLM_INDMNTY_AMT != nil {
		return *m.CLM_INDMNTY_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_RSRV_AMT() float64 {
	if m != nil && m.CLM_RSRV_AMT != nil {
		return *m.CLM_RSRV_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_INITL_RSRV_AMT() float64 {
	if m != nil && m.CLM_INITL_RSRV_AMT != nil {
		return *m.CLM_INITL_RSRV_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetDIFF_INTL_RSRV_PYMNT() float64 {
	if m != nil && m.DIFF_INTL_RSRV_PYMNT != nil {
		return *m.DIFF_INTL_RSRV_PYMNT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_FEE_AMT() float64 {
	if m != nil && m.CLM_FEE_AMT != nil {
		return *m.CLM_FEE_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetTOT_CLM_AMT() float64 {
	if m != nil && m.TOT_CLM_AMT != nil {
		return *m.TOT_CLM_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_DTTM() int64 {
	if m != nil && m.INCDNT_DTTM != nil {
		return *m.INCDNT_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_HOUR_OF_DAY() float64 {
	if m != nil && m.INCDNT_HOUR_OF_DAY != nil {
		return *m.INCDNT_HOUR_OF_DAY
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_DAY_OF_WEEK() float64 {
	if m != nil && m.INCDNT_DAY_OF_WEEK != nil {
		return *m.INCDNT_DAY_OF_WEEK
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_RGSTR_DTTM() int64 {
	if m != nil && m.CLM_RGSTR_DTTM != nil {
		return *m.CLM_RGSTR_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetDAYS_INCDNT_RGSTR() float64 {
	if m != nil && m.DAYS_INCDNT_RGSTR != nil {
		return *m.DAYS_INCDNT_RGSTR
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_LAST_CLSD_DTTM() int64 {
	if m != nil && m.CLM_LAST_CLSD_DTTM != nil {
		return *m.CLM_LAST_CLSD_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_LAST_STTLM_DTTM() int64 {
	if m != nil && m.CLM_LAST_STTLM_DTTM != nil {
		return *m.CLM_LAST_STTLM_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_LGL_FLG() float64 {
	if m != nil && m.CLM_LGL_FLG != nil {
		return *m.CLM_LGL_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_NOTIF_CHNL_CD() string {
	if m != nil && m.CLM_NOTIF_CHNL_CD != nil {
		return *m.CLM_NOTIF_CHNL_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_NOTIF_SRC_CD() string {
	if m != nil && m.CLM_NOTIF_SRC_CD != nil {
		return *m.CLM_NOTIF_SRC_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_NOTIF_TO_CLM_HNDL_DTTM() int64 {
	if m != nil && m.CLM_NOTIF_TO_CLM_HNDL_DTTM != nil {
		return *m.CLM_NOTIF_TO_CLM_HNDL_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetDAYS_NOTIF_CHNL_HNDL() float64 {
	if m != nil && m.DAYS_NOTIF_CHNL_HNDL != nil {
		return *m.DAYS_NOTIF_CHNL_HNDL
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_RCVR_PAID_AMT() float64 {
	if m != nil && m.CLM_RCVR_PAID_AMT != nil {
		return *m.CLM_RCVR_PAID_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_RSRV_STTLM_TRTY_AMT() float64 {
	if m != nil && m.CLM_RSRV_STTLM_TRTY_AMT != nil {
		return *m.CLM_RSRV_STTLM_TRTY_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_DESC() string {
	if m != nil && m.INCDNT_DESC != nil {
		return *m.INCDNT_DESC
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_LOC_DESC() string {
	if m != nil && m.INCDNT_LOC_DESC != nil {
		return *m.INCDNT_LOC_DESC
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_LOC_GPS_CRDNT() string {
	if m != nil && m.INCDNT_LOC_GPS_CRDNT != nil {
		return *m.INCDNT_LOC_GPS_CRDNT
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_MULTI_VEH_INCDNT_FLG() float64 {
	if m != nil && m.INCDNT_MULTI_VEH_INCDNT_FLG != nil {
		return *m.INCDNT_MULTI_VEH_INCDNT_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_OTH_OBJ_FLG() float64 {
	if m != nil && m.INCDNT_OTH_OBJ_FLG != nil {
		return *m.INCDNT_OTH_OBJ_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_PLCE_AT_SCENE_FLG() float64 {
	if m != nil && m.INCDNT_PLCE_AT_SCENE_FLG != nil {
		return *m.INCDNT_PLCE_AT_SCENE_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_TOTAL_VEH_NO() float64 {
	if m != nil && m.INCDNT_TOTAL_VEH_NO != nil {
		return *m.INCDNT_TOTAL_VEH_NO
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_CNTRY_CD() string {
	if m != nil && m.INCDNT_CNTRY_CD != nil {
		return *m.INCDNT_CNTRY_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_ABROAD_FLG() float64 {
	if m != nil && m.INCDNT_ABROAD_FLG != nil {
		return *m.INCDNT_ABROAD_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_ADDR_LN_1() string {
	if m != nil && m.INCDNT_ADDR_LN_1 != nil {
		return *m.INCDNT_ADDR_LN_1
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_CITY_NM() string {
	if m != nil && m.INCDNT_CITY_NM != nil {
		return *m.INCDNT_CITY_NM
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_POSTAL_CD() string {
	if m != nil && m.INCDNT_POSTAL_CD != nil {
		return *m.INCDNT_POSTAL_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetINCDNT_DISTRICT_NM() string {
	if m != nil && m.INCDNT_DISTRICT_NM != nil {
		return *m.INCDNT_DISTRICT_NM
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetCNTRCT_BUS_ID() string {
	if m != nil && m.CNTRCT_BUS_ID != nil {
		return *m.CNTRCT_BUS_ID
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetCNTRCT_ISSUE_DTTM() int64 {
	if m != nil && m.CNTRCT_ISSUE_DTTM != nil {
		return *m.CNTRCT_ISSUE_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetDAYS_INCDNT_CNTRCT_ISSUE() float64 {
	if m != nil && m.DAYS_INCDNT_CNTRCT_ISSUE != nil {
		return *m.DAYS_INCDNT_CNTRCT_ISSUE
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetDAYS_RGSTR_CNTRCT_ISSUE() float64 {
	if m != nil && m.DAYS_RGSTR_CNTRCT_ISSUE != nil {
		return *m.DAYS_RGSTR_CNTRCT_ISSUE
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCNTRCT_NEXT_RNWL_DTTM() int64 {
	if m != nil && m.CNTRCT_NEXT_RNWL_DTTM != nil {
		return *m.CNTRCT_NEXT_RNWL_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCNTRCT_EXPRY_DTTM() int64 {
	if m != nil && m.CNTRCT_EXPRY_DTTM != nil {
		return *m.CNTRCT_EXPRY_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetDAYS_INCDNT_CNTRCT_EXPRY() float64 {
	if m != nil && m.DAYS_INCDNT_CNTRCT_EXPRY != nil {
		return *m.DAYS_INCDNT_CNTRCT_EXPRY
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPYMT_METHOD_CD() string {
	if m != nil && m.PYMT_METHOD_CD != nil {
		return *m.PYMT_METHOD_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPYMT_MODE_CD() string {
	if m != nil && m.PYMT_MODE_CD != nil {
		return *m.PYMT_MODE_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetGWP_ANN_AMT() float64 {
	if m != nil && m.GWP_ANN_AMT != nil {
		return *m.GWP_ANN_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetTSI_AMT() float64 {
	if m != nil && m.TSI_AMT != nil {
		return *m.TSI_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetRATIO_CLM_AMT_TSI_AMT() float64 {
	if m != nil && m.RATIO_CLM_AMT_TSI_AMT != nil {
		return *m.RATIO_CLM_AMT_TSI_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_BUS_ID() string {
	if m != nil && m.PLCY_BUS_ID != nil {
		return *m.PLCY_BUS_ID
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_CNTRCT_CTGRY_CD() string {
	if m != nil && m.PLCY_CNTRCT_CTGRY_CD != nil {
		return *m.PLCY_CNTRCT_CTGRY_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_CNTRCT_STTS_CD() string {
	if m != nil && m.PLCY_CNTRCT_STTS_CD != nil {
		return *m.PLCY_CNTRCT_STTS_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_CNTRCT_TYP_CD() string {
	if m != nil && m.PLCY_CNTRCT_TYP_CD != nil {
		return *m.PLCY_CNTRCT_TYP_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_PRM_ACCT_STTS_CD() string {
	if m != nil && m.PLCY_PRM_ACCT_STTS_CD != nil {
		return *m.PLCY_PRM_ACCT_STTS_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_MNTH_PYMT_DUE_DAY_NO() float64 {
	if m != nil && m.PLCY_MNTH_PYMT_DUE_DAY_NO != nil {
		return *m.PLCY_MNTH_PYMT_DUE_DAY_NO
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_PRM_CVR_FLG() float64 {
	if m != nil && m.PLCY_PRM_CVR_FLG != nil {
		return *m.PLCY_PRM_CVR_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_PRM_CVR_FLG_UPDT_DT() int64 {
	if m != nil && m.PLCY_PRM_CVR_FLG_UPDT_DT != nil {
		return *m.PLCY_PRM_CVR_FLG_UPDT_DT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_PRM_PAID_UNTIL_DT() int64 {
	if m != nil && m.PLCY_PRM_PAID_UNTIL_DT != nil {
		return *m.PLCY_PRM_PAID_UNTIL_DT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_ISSUE_DTTM() int64 {
	if m != nil && m.PLCY_ISSUE_DTTM != nil {
		return *m.PLCY_ISSUE_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetDAYS_INCDNT_PLCY_ISSUE() float64 {
	if m != nil && m.DAYS_INCDNT_PLCY_ISSUE != nil {
		return *m.DAYS_INCDNT_PLCY_ISSUE
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetDAYS_RGSTR_PLCY_ISSUE() float64 {
	if m != nil && m.DAYS_RGSTR_PLCY_ISSUE != nil {
		return *m.DAYS_RGSTR_PLCY_ISSUE
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_NEXT_RNWL_DTTM() int64 {
	if m != nil && m.PLCY_NEXT_RNWL_DTTM != nil {
		return *m.PLCY_NEXT_RNWL_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_EXPRY_DTTM() int64 {
	if m != nil && m.PLCY_EXPRY_DTTM != nil {
		return *m.PLCY_EXPRY_DTTM
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetDAYS_INCDNT_PLCY_EXPRY() float64 {
	if m != nil && m.DAYS_INCDNT_PLCY_EXPRY != nil {
		return *m.DAYS_INCDNT_PLCY_EXPRY
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_PLCY_HLD_RSPN_PCT() float64 {
	if m != nil && m.CLM_PLCY_HLD_RSPN_PCT != nil {
		return *m.CLM_PLCY_HLD_RSPN_PCT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetFRAUD_FLG() string {
	if m != nil && m.FRAUD_FLG != nil {
		return *m.FRAUD_FLG
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetINVSTGT_FLG() float64 {
	if m != nil && m.INVSTGT_FLG != nil {
		return *m.INVSTGT_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINVSTGT_STRT_DT() int64 {
	if m != nil && m.INVSTGT_STRT_DT != nil {
		return *m.INVSTGT_STRT_DT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetINVSTGT_END_DT() int64 {
	if m != nil && m.INVSTGT_END_DT != nil {
		return *m.INVSTGT_END_DT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBI_FLG() float64 {
	if m != nil && m.BI_FLG != nil {
		return *m.BI_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetOBJ_TTL_LOSS_FLG() float64 {
	if m != nil && m.OBJ_TTL_LOSS_FLG != nil {
		return *m.OBJ_TTL_LOSS_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetCLM_OBJ_ROLE_CD() string {
	if m != nil && m.CLM_OBJ_ROLE_CD != nil {
		return *m.CLM_OBJ_ROLE_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetOBJ_TYP_CD() string {
	if m != nil && m.OBJ_TYP_CD != nil {
		return *m.OBJ_TYP_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_TYP_CD() string {
	if m != nil && m.VEH_TYP_CD != nil {
		return *m.VEH_TYP_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_USE_TYP_CD() string {
	if m != nil && m.VEH_USE_TYP_CD != nil {
		return *m.VEH_USE_TYP_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetOBJ_BUS_ID() string {
	if m != nil && m.OBJ_BUS_ID != nil {
		return *m.OBJ_BUS_ID
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_VIN() string {
	if m != nil && m.VEH_VIN != nil {
		return *m.VEH_VIN
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_MNFCTR_DT() string {
	if m != nil && m.VEH_MNFCTR_DT != nil {
		return *m.VEH_MNFCTR_DT
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_AGE_YRS() float64 {
	if m != nil && m.VEH_AGE_YRS != nil {
		return *m.VEH_AGE_YRS
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_COLOR_TXT() string {
	if m != nil && m.VEH_COLOR_TXT != nil {
		return *m.VEH_COLOR_TXT
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_MNFCTR_NM() string {
	if m != nil && m.VEH_MNFCTR_NM != nil {
		return *m.VEH_MNFCTR_NM
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_MODEL_TXT() string {
	if m != nil && m.VEH_MODEL_TXT != nil {
		return *m.VEH_MODEL_TXT
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_MODEL_YR_NO() string {
	if m != nil && m.VEH_MODEL_YR_NO != nil {
		return *m.VEH_MODEL_YR_NO
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_PRCH_AMT() float64 {
	if m != nil && m.VEH_PRCH_AMT != nil {
		return *m.VEH_PRCH_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_LEASED_FLG() float64 {
	if m != nil && m.VEH_LEASED_FLG != nil {
		return *m.VEH_LEASED_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_LCNS_PLATE_NO_TXT() string {
	if m != nil && m.VEH_LCNS_PLATE_NO_TXT != nil {
		return *m.VEH_LCNS_PLATE_NO_TXT
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetVEH_PRCH_DT() int64 {
	if m != nil && m.VEH_PRCH_DT != nil {
		return *m.VEH_PRCH_DT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetRATIO_CLM_AMT_VEH_PRCH_AMT() float64 {
	if m != nil && m.RATIO_CLM_AMT_VEH_PRCH_AMT != nil {
		return *m.RATIO_CLM_AMT_VEH_PRCH_AMT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetTP_VEH_AGE_YRS() float64 {
	if m != nil && m.TP_VEH_AGE_YRS != nil {
		return *m.TP_VEH_AGE_YRS
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPLCE_RPRT_FLG() float64 {
	if m != nil && m.PLCE_RPRT_FLG != nil {
		return *m.PLCE_RPRT_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPRTY_TYP_CD() string {
	if m != nil && m.PRTY_TYP_CD != nil {
		return *m.PRTY_TYP_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetLE_BUS_TYP_CD() string {
	if m != nil && m.LE_BUS_TYP_CD != nil {
		return *m.LE_BUS_TYP_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPE_GENDER_TYP_CD() string {
	if m != nil && m.PE_GENDER_TYP_CD != nil {
		return *m.PE_GENDER_TYP_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPE_MRTL_STTS_CD() string {
	if m != nil && m.PE_MRTL_STTS_CD != nil {
		return *m.PE_MRTL_STTS_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPE_OCC_TYP_CD() string {
	if m != nil && m.PE_OCC_TYP_CD != nil {
		return *m.PE_OCC_TYP_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPRTY_TAX_NO_TXT() string {
	if m != nil && m.PRTY_TAX_NO_TXT != nil {
		return *m.PRTY_TAX_NO_TXT
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPRTY_WATCH_LIST_FLG() float64 {
	if m != nil && m.PRTY_WATCH_LIST_FLG != nil {
		return *m.PRTY_WATCH_LIST_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_HLD_NM() string {
	if m != nil && m.PLCY_HLD_NM != nil {
		return *m.PLCY_HLD_NM
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPE_BIRTH_DT() int64 {
	if m != nil && m.PE_BIRTH_DT != nil {
		return *m.PE_BIRTH_DT
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPLCY_HLD_AGE() float64 {
	if m != nil && m.PLCY_HLD_AGE != nil {
		return *m.PLCY_HLD_AGE
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetPRTY_CNTRY_CD() string {
	if m != nil && m.PRTY_CNTRY_CD != nil {
		return *m.PRTY_CNTRY_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPRTY_ADDR_LN_1() string {
	if m != nil && m.PRTY_ADDR_LN_1 != nil {
		return *m.PRTY_ADDR_LN_1
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPRTY_CITY_NM() string {
	if m != nil && m.PRTY_CITY_NM != nil {
		return *m.PRTY_CITY_NM
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPRTY_POSTAL_CD() string {
	if m != nil && m.PRTY_POSTAL_CD != nil {
		return *m.PRTY_POSTAL_CD
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetPRTY_DISTRICT_NM() string {
	if m != nil && m.PRTY_DISTRICT_NM != nil {
		return *m.PRTY_DISTRICT_NM
	}
	return ""
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I001() float64 {
	if m != nil && m.BR002_I001 != nil {
		return *m.BR002_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I002() float64 {
	if m != nil && m.BR002_I002 != nil {
		return *m.BR002_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I003() float64 {
	if m != nil && m.BR002_I003 != nil {
		return *m.BR002_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I004() float64 {
	if m != nil && m.BR002_I004 != nil {
		return *m.BR002_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I005() float64 {
	if m != nil && m.BR002_I005 != nil {
		return *m.BR002_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I006() float64 {
	if m != nil && m.BR002_I006 != nil {
		return *m.BR002_I006
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I007() float64 {
	if m != nil && m.BR002_I007 != nil {
		return *m.BR002_I007
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I008() float64 {
	if m != nil && m.BR002_I008 != nil {
		return *m.BR002_I008
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I009() float64 {
	if m != nil && m.BR002_I009 != nil {
		return *m.BR002_I009
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I010() float64 {
	if m != nil && m.BR002_I010 != nil {
		return *m.BR002_I010
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I011() float64 {
	if m != nil && m.BR002_I011 != nil {
		return *m.BR002_I011
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I012() float64 {
	if m != nil && m.BR002_I012 != nil {
		return *m.BR002_I012
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I013() float64 {
	if m != nil && m.BR002_I013 != nil {
		return *m.BR002_I013
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I014() float64 {
	if m != nil && m.BR002_I014 != nil {
		return *m.BR002_I014
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I015() float64 {
	if m != nil && m.BR002_I015 != nil {
		return *m.BR002_I015
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I016() float64 {
	if m != nil && m.BR002_I016 != nil {
		return *m.BR002_I016
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I017() float64 {
	if m != nil && m.BR002_I017 != nil {
		return *m.BR002_I017
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I018() float64 {
	if m != nil && m.BR002_I018 != nil {
		return *m.BR002_I018
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I019() float64 {
	if m != nil && m.BR002_I019 != nil {
		return *m.BR002_I019
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I020() float64 {
	if m != nil && m.BR002_I020 != nil {
		return *m.BR002_I020
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I021() float64 {
	if m != nil && m.BR002_I021 != nil {
		return *m.BR002_I021
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I022() float64 {
	if m != nil && m.BR002_I022 != nil {
		return *m.BR002_I022
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I023() float64 {
	if m != nil && m.BR002_I023 != nil {
		return *m.BR002_I023
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I024() float64 {
	if m != nil && m.BR002_I024 != nil {
		return *m.BR002_I024
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I025() float64 {
	if m != nil && m.BR002_I025 != nil {
		return *m.BR002_I025
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I026() float64 {
	if m != nil && m.BR002_I026 != nil {
		return *m.BR002_I026
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I027() float64 {
	if m != nil && m.BR002_I027 != nil {
		return *m.BR002_I027
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I028() float64 {
	if m != nil && m.BR002_I028 != nil {
		return *m.BR002_I028
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I029() float64 {
	if m != nil && m.BR002_I029 != nil {
		return *m.BR002_I029
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR002_I030() float64 {
	if m != nil && m.BR002_I030 != nil {
		return *m.BR002_I030
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I001() float64 {
	if m != nil && m.BR003_I001 != nil {
		return *m.BR003_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I002() float64 {
	if m != nil && m.BR003_I002 != nil {
		return *m.BR003_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I003() float64 {
	if m != nil && m.BR003_I003 != nil {
		return *m.BR003_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I004() float64 {
	if m != nil && m.BR003_I004 != nil {
		return *m.BR003_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I005() float64 {
	if m != nil && m.BR003_I005 != nil {
		return *m.BR003_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I006() float64 {
	if m != nil && m.BR003_I006 != nil {
		return *m.BR003_I006
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I007() float64 {
	if m != nil && m.BR003_I007 != nil {
		return *m.BR003_I007
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I008() float64 {
	if m != nil && m.BR003_I008 != nil {
		return *m.BR003_I008
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I009() float64 {
	if m != nil && m.BR003_I009 != nil {
		return *m.BR003_I009
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I010() float64 {
	if m != nil && m.BR003_I010 != nil {
		return *m.BR003_I010
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I011() float64 {
	if m != nil && m.BR003_I011 != nil {
		return *m.BR003_I011
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I012() float64 {
	if m != nil && m.BR003_I012 != nil {
		return *m.BR003_I012
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I013() float64 {
	if m != nil && m.BR003_I013 != nil {
		return *m.BR003_I013
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I014() float64 {
	if m != nil && m.BR003_I014 != nil {
		return *m.BR003_I014
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I015() float64 {
	if m != nil && m.BR003_I015 != nil {
		return *m.BR003_I015
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I016() float64 {
	if m != nil && m.BR003_I016 != nil {
		return *m.BR003_I016
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I017() float64 {
	if m != nil && m.BR003_I017 != nil {
		return *m.BR003_I017
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I018() float64 {
	if m != nil && m.BR003_I018 != nil {
		return *m.BR003_I018
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I019() float64 {
	if m != nil && m.BR003_I019 != nil {
		return *m.BR003_I019
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I020() float64 {
	if m != nil && m.BR003_I020 != nil {
		return *m.BR003_I020
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I021() float64 {
	if m != nil && m.BR003_I021 != nil {
		return *m.BR003_I021
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I022() float64 {
	if m != nil && m.BR003_I022 != nil {
		return *m.BR003_I022
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I023() float64 {
	if m != nil && m.BR003_I023 != nil {
		return *m.BR003_I023
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I024() float64 {
	if m != nil && m.BR003_I024 != nil {
		return *m.BR003_I024
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I025() float64 {
	if m != nil && m.BR003_I025 != nil {
		return *m.BR003_I025
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I026() float64 {
	if m != nil && m.BR003_I026 != nil {
		return *m.BR003_I026
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I027() float64 {
	if m != nil && m.BR003_I027 != nil {
		return *m.BR003_I027
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I028() float64 {
	if m != nil && m.BR003_I028 != nil {
		return *m.BR003_I028
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I029() float64 {
	if m != nil && m.BR003_I029 != nil {
		return *m.BR003_I029
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I030() float64 {
	if m != nil && m.BR003_I030 != nil {
		return *m.BR003_I030
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I031() float64 {
	if m != nil && m.BR003_I031 != nil {
		return *m.BR003_I031
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I032() float64 {
	if m != nil && m.BR003_I032 != nil {
		return *m.BR003_I032
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I033() float64 {
	if m != nil && m.BR003_I033 != nil {
		return *m.BR003_I033
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I034() float64 {
	if m != nil && m.BR003_I034 != nil {
		return *m.BR003_I034
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR003_I035() float64 {
	if m != nil && m.BR003_I035 != nil {
		return *m.BR003_I035
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR006_I001() float64 {
	if m != nil && m.BR006_I001 != nil {
		return *m.BR006_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR006_I002() float64 {
	if m != nil && m.BR006_I002 != nil {
		return *m.BR006_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR006_I003() float64 {
	if m != nil && m.BR006_I003 != nil {
		return *m.BR006_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR006_I004() float64 {
	if m != nil && m.BR006_I004 != nil {
		return *m.BR006_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR006_I005() float64 {
	if m != nil && m.BR006_I005 != nil {
		return *m.BR006_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR006_I006() float64 {
	if m != nil && m.BR006_I006 != nil {
		return *m.BR006_I006
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR006_I007() float64 {
	if m != nil && m.BR006_I007 != nil {
		return *m.BR006_I007
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR012_I001() float64 {
	if m != nil && m.BR012_I001 != nil {
		return *m.BR012_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR012_I002() float64 {
	if m != nil && m.BR012_I002 != nil {
		return *m.BR012_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR012_I003() float64 {
	if m != nil && m.BR012_I003 != nil {
		return *m.BR012_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR012_I004() float64 {
	if m != nil && m.BR012_I004 != nil {
		return *m.BR012_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR012_I005() float64 {
	if m != nil && m.BR012_I005 != nil {
		return *m.BR012_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR031_I001() float64 {
	if m != nil && m.BR031_I001 != nil {
		return *m.BR031_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR031_I002() float64 {
	if m != nil && m.BR031_I002 != nil {
		return *m.BR031_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR031_I003() float64 {
	if m != nil && m.BR031_I003 != nil {
		return *m.BR031_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR031_I004() float64 {
	if m != nil && m.BR031_I004 != nil {
		return *m.BR031_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR031_I005() float64 {
	if m != nil && m.BR031_I005 != nil {
		return *m.BR031_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR031_I006() float64 {
	if m != nil && m.BR031_I006 != nil {
		return *m.BR031_I006
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR031_I007() float64 {
	if m != nil && m.BR031_I007 != nil {
		return *m.BR031_I007
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR038_I001() float64 {
	if m != nil && m.BR038_I001 != nil {
		return *m.BR038_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR038_I002() float64 {
	if m != nil && m.BR038_I002 != nil {
		return *m.BR038_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR038_I003() float64 {
	if m != nil && m.BR038_I003 != nil {
		return *m.BR038_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR038_I004() float64 {
	if m != nil && m.BR038_I004 != nil {
		return *m.BR038_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR038_I005() float64 {
	if m != nil && m.BR038_I005 != nil {
		return *m.BR038_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR038_I006() float64 {
	if m != nil && m.BR038_I006 != nil {
		return *m.BR038_I006
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR055_I001() float64 {
	if m != nil && m.BR055_I001 != nil {
		return *m.BR055_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR055_I002() float64 {
	if m != nil && m.BR055_I002 != nil {
		return *m.BR055_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR055_I003() float64 {
	if m != nil && m.BR055_I003 != nil {
		return *m.BR055_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR055_I004() float64 {
	if m != nil && m.BR055_I004 != nil {
		return *m.BR055_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR060_I001() float64 {
	if m != nil && m.BR060_I001 != nil {
		return *m.BR060_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR060_I002() float64 {
	if m != nil && m.BR060_I002 != nil {
		return *m.BR060_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR060_I003() float64 {
	if m != nil && m.BR060_I003 != nil {
		return *m.BR060_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR060_I004() float64 {
	if m != nil && m.BR060_I004 != nil {
		return *m.BR060_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR060_I005() float64 {
	if m != nil && m.BR060_I005 != nil {
		return *m.BR060_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR060_I006() float64 {
	if m != nil && m.BR060_I006 != nil {
		return *m.BR060_I006
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR063_I001() float64 {
	if m != nil && m.BR063_I001 != nil {
		return *m.BR063_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR063_I002() float64 {
	if m != nil && m.BR063_I002 != nil {
		return *m.BR063_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR063_I003() float64 {
	if m != nil && m.BR063_I003 != nil {
		return *m.BR063_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR063_I004() float64 {
	if m != nil && m.BR063_I004 != nil {
		return *m.BR063_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR063_I005() float64 {
	if m != nil && m.BR063_I005 != nil {
		return *m.BR063_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR076_I001() float64 {
	if m != nil && m.BR076_I001 != nil {
		return *m.BR076_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR095_I001() float64 {
	if m != nil && m.BR095_I001 != nil {
		return *m.BR095_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR095_I002() float64 {
	if m != nil && m.BR095_I002 != nil {
		return *m.BR095_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR095_I003() float64 {
	if m != nil && m.BR095_I003 != nil {
		return *m.BR095_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR095_I004() float64 {
	if m != nil && m.BR095_I004 != nil {
		return *m.BR095_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR095_I005() float64 {
	if m != nil && m.BR095_I005 != nil {
		return *m.BR095_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR096_I001() float64 {
	if m != nil && m.BR096_I001 != nil {
		return *m.BR096_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR096_I002() float64 {
	if m != nil && m.BR096_I002 != nil {
		return *m.BR096_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR096_I003() float64 {
	if m != nil && m.BR096_I003 != nil {
		return *m.BR096_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR096_I004() float64 {
	if m != nil && m.BR096_I004 != nil {
		return *m.BR096_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR096_I005() float64 {
	if m != nil && m.BR096_I005 != nil {
		return *m.BR096_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR102_I001() float64 {
	if m != nil && m.BR102_I001 != nil {
		return *m.BR102_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR103_I001() float64 {
	if m != nil && m.BR103_I001 != nil {
		return *m.BR103_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR103_I002() float64 {
	if m != nil && m.BR103_I002 != nil {
		return *m.BR103_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR108_I001() float64 {
	if m != nil && m.BR108_I001 != nil {
		return *m.BR108_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR108_I002() float64 {
	if m != nil && m.BR108_I002 != nil {
		return *m.BR108_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR108_I003() float64 {
	if m != nil && m.BR108_I003 != nil {
		return *m.BR108_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR109_I001() float64 {
	if m != nil && m.BR109_I001 != nil {
		return *m.BR109_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR109_I002() float64 {
	if m != nil && m.BR109_I002 != nil {
		return *m.BR109_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR109_I003() float64 {
	if m != nil && m.BR109_I003 != nil {
		return *m.BR109_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR109_I004() float64 {
	if m != nil && m.BR109_I004 != nil {
		return *m.BR109_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR109_I005() float64 {
	if m != nil && m.BR109_I005 != nil {
		return *m.BR109_I005
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR109_I006() float64 {
	if m != nil && m.BR109_I006 != nil {
		return *m.BR109_I006
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR109_I007() float64 {
	if m != nil && m.BR109_I007 != nil {
		return *m.BR109_I007
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR109_I008() float64 {
	if m != nil && m.BR109_I008 != nil {
		return *m.BR109_I008
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR109_I009() float64 {
	if m != nil && m.BR109_I009 != nil {
		return *m.BR109_I009
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR109_I010() float64 {
	if m != nil && m.BR109_I010 != nil {
		return *m.BR109_I010
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR110_I001() float64 {
	if m != nil && m.BR110_I001 != nil {
		return *m.BR110_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR111_I001() float64 {
	if m != nil && m.BR111_I001 != nil {
		return *m.BR111_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR112_I001() float64 {
	if m != nil && m.BR112_I001 != nil {
		return *m.BR112_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR113_I001() float64 {
	if m != nil && m.BR113_I001 != nil {
		return *m.BR113_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR114_I001() float64 {
	if m != nil && m.BR114_I001 != nil {
		return *m.BR114_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR114_I002() float64 {
	if m != nil && m.BR114_I002 != nil {
		return *m.BR114_I002
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR114_I003() float64 {
	if m != nil && m.BR114_I003 != nil {
		return *m.BR114_I003
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR114_I004() float64 {
	if m != nil && m.BR114_I004 != nil {
		return *m.BR114_I004
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR115_I001() float64 {
	if m != nil && m.BR115_I001 != nil {
		return *m.BR115_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR117_I001() float64 {
	if m != nil && m.BR117_I001 != nil {
		return *m.BR117_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR118_I001() float64 {
	if m != nil && m.BR118_I001 != nil {
		return *m.BR118_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR119_I001() float64 {
	if m != nil && m.BR119_I001 != nil {
		return *m.BR119_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR121_I001() float64 {
	if m != nil && m.BR121_I001 != nil {
		return *m.BR121_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR122_I001() float64 {
	if m != nil && m.BR122_I001 != nil {
		return *m.BR122_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR123_I001() float64 {
	if m != nil && m.BR123_I001 != nil {
		return *m.BR123_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetBR125_I001() float64 {
	if m != nil && m.BR125_I001 != nil {
		return *m.BR125_I001
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetNEW_INVSTGT_FLG() float64 {
	if m != nil && m.NEW_INVSTGT_FLG != nil {
		return *m.NEW_INVSTGT_FLG
	}
	return 0
}

func (m *ProtoListClaim_ProtoClaim) GetLOAD_DATE() int64 {
	if m != nil && m.LOAD_DATE != nil {
		return *m.LOAD_DATE
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoListClaim)(nil), "protoclaim.ProtoListClaim")
	proto.RegisterType((*ProtoListClaim_ProtoClaim)(nil), "protoclaim.ProtoListClaim.ProtoClaim")
}
