// Code generated by protoc-gen-go.
// source: score.proto
// DO NOT EDIT!

/*
Package protoclaim is a generated protocol buffer package.

It is generated from these files:
	score.proto

It has these top-level messages:
	ProtoListScore
*/
package protoclaim

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ProtoListScore struct {
	Scores           []*ProtoListScore_ProtoScore `protobuf:"bytes,1,rep,name=Scores" json:"Scores,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *ProtoListScore) Reset()         { *m = ProtoListScore{} }
func (m *ProtoListScore) String() string { return proto.CompactTextString(m) }
func (*ProtoListScore) ProtoMessage()    {}

func (m *ProtoListScore) GetScores() []*ProtoListScore_ProtoScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

type ProtoListScore_ProtoScore struct {
	GLB_OE_ID        *int64   `protobuf:"varint,1,opt,name=GLB_OE_ID" json:"GLB_OE_ID,omitempty"`
	CLM_BUS_ID       *string  `protobuf:"bytes,2,opt,name=CLM_BUS_ID" json:"CLM_BUS_ID,omitempty"`
	SCORE            *float64 `protobuf:"fixed64,3,opt,name=SCORE" json:"SCORE,omitempty"`
	MODEL            *string  `protobuf:"bytes,4,opt,name=MODEL" json:"MODEL,omitempty"`
	CREATE_DT        *int64   `protobuf:"varint,5,opt,name=CREATE_DT" json:"CREATE_DT,omitempty"`
	CREATE_DT_TS     *int64   `protobuf:"varint,6,opt,name=CREATE_DT_TS" json:"CREATE_DT_TS,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoListScore_ProtoScore) Reset()         { *m = ProtoListScore_ProtoScore{} }
func (m *ProtoListScore_ProtoScore) String() string { return proto.CompactTextString(m) }
func (*ProtoListScore_ProtoScore) ProtoMessage()    {}

func (m *ProtoListScore_ProtoScore) GetGLB_OE_ID() int64 {
	if m != nil && m.GLB_OE_ID != nil {
		return *m.GLB_OE_ID
	}
	return 0
}

func (m *ProtoListScore_ProtoScore) GetCLM_BUS_ID() string {
	if m != nil && m.CLM_BUS_ID != nil {
		return *m.CLM_BUS_ID
	}
	return ""
}

func (m *ProtoListScore_ProtoScore) GetSCORE() float64 {
	if m != nil && m.SCORE != nil {
		return *m.SCORE
	}
	return 0
}

func (m *ProtoListScore_ProtoScore) GetMODEL() string {
	if m != nil && m.MODEL != nil {
		return *m.MODEL
	}
	return ""
}

func (m *ProtoListScore_ProtoScore) GetCREATE_DT() int64 {
	if m != nil && m.CREATE_DT != nil {
		return *m.CREATE_DT
	}
	return 0
}

func (m *ProtoListScore_ProtoScore) GetCREATE_DT_TS() int64 {
	if m != nil && m.CREATE_DT_TS != nil {
		return *m.CREATE_DT_TS
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoListScore)(nil), "protoclaim.ProtoListScore")
	proto.RegisterType((*ProtoListScore_ProtoScore)(nil), "protoclaim.ProtoListScore.ProtoScore")
}
